function [dataPth,hhourPth,databasePth,csi_netPth] = fr_get_local_path


%This file is generated by fr_set_site.m
%Please do not edit - use fr_set_site instead!


dataPth  = 'T:\Research_Groups\Sean_Smukler\SALdata\GHGdata\SAL Picarro All Data\met-data\data\';
hhourPth  = 'e:\junk\SAL\hhour\';
databasePth  = 'e:\junk\SAL\hhour\Database\';
csi_netPth  = 'T:\Research_Groups\Sean_Smukler\SALdata\GHGdata\SAL Picarro All Data\met-data\data\';
