                opt = optimoptions('lsqcurvefit','MaxFunctionEvaluations',1000,...
                                'FunctionTolerance',functionTolerance,...
                                'algorithm','levenberg-marquardt',...
                                'Display','off');
                            
                            
co2fitOptions = fitoptions('Method','NonlinearLeastSquares',...
                        'Robust','off',...
                        'StartPoint',[ -0.1 400],...
                        'Lower',[-Inf 300],...
                        'Upper',[0 5000],...
                        'TolFun',1e-8,...
                        'TolX',1e-8,...
                        'MaxIter',600,...
                        'DiffMinChange',1e-8,...
                        'DiffMaxChange',0.1,...
                        'MaxFunEvals',600);   %1600                              
                    

dateIn = [datenum(2021,8,[1:30])];   
for currentDate = dateIn
    try
        dataStruct = UdeM_ACS_calc_one_day(currentDate,'UdeM',0,1,[],[],1);
        fprintf('\n\n\n');
    catch
        fprintf('\n\n**** Error processing %s\n\n',datestr(dateIn));
    end
end