%%
dateIn = datenum(2023,8,17);
configIn = fr_get_init('SAL',dateIn);
dataOut = SAL_read_one_day(dateIn,configIn);

return

%%
[tv,climateData] = fr_read_csi(wildCard,dateIn,chanInd,tableID,verbose_flag,timeUnit,roundType,tv_input_format)

%%

t=readtable('T:\Research_Groups\Sean_Smukler\SALdata\GHGdata\SAL Picarro All Data\met-data\data\230817\230817_ACS_CR23X_final_storage_2.dat');

%%
tt = readtable('var_102.txt');
tt(:,[1 3])=[];
ttc = table2cell(tt);

for cntCell = 1:size(ttc,1)
    fprintf('''%s'',',char(ttc(cntCell)));
end

    
%%
fileName = 'T:\Research_Groups\Sean_Smukler\SALdata\GHGdata\SAL Picarro All Data\met-data\data\230817\230817_ACS_CR23X_final_storage_2.dat';
chanInd = [];
tableID = 101;
% defaultNaN = NaN;
%assign_in = 'caller';
timeUnit = 'SEC';
roundType = 1;
tv_input_format = [1 2 3 4];
varNames_101 = {'tableID','Year_RTM','Day_RTM','Hour_Minute_RTM','Seconds_RTM',...
            'ChNum','Tc_1','Tc_2','Tc_3','Tc_4','Tc_5','Tc_6',...
            'Tc_7','Tc_8','Tc_9','Tc_10','Tc_11','Tc_12','Tc_13',...
            'Tc_14','Tc_15','Tc_16','Tc_17','Tc_18','Tc_19','Tc_20',...
            'Tc_21','Tc_22','Tc_23','Tc_24','Tc_25'};
[~,~,~,dataOut_HF] = fr_read_csi_file(fileName,chanInd,varNames_101,tableID,timeUnit,roundType,tv_input_format);
%%
fileName = 'T:\Research_Groups\Sean_Smukler\SALdata\GHGdata\SAL Picarro All Data\met-data\data\230817\230817_ACS_CR23X_final_storage_1.dat';
chanInd = [];
tableID = 102;
% defaultNaN = NaN;
%assign_in = 'caller';
timeUnit = 'SEC';
roundType = 1;
tv_input_format = [1 2 3 4];
varNames_102 = {'tableID','Year_RTM','Day_RTM','Hour_Minute_RTM','BattV_AVG',...
                'PanelT_AVG','PumpBoxT_AVG','BattV_MAX','PanelT_MAX','PumpBoxT_MAX',...
                'BattV_MIN','PanelT_MIN','PumpBoxT_MIN','BattV_STD','PanelT_STD',...
                'PumpBoxT_STD','Tc_1_AVG','Tc_2_AVG','Tc_3_AVG','Tc_4_AVG',...
                'Tc_5_AVG','Tc_6_AVG','Tc_7_AVG','Tc_8_AVG','Tc_9_AVG',...
                'Tc_10_AVG','Tc_11_AVG','Tc_12_AVG','Tc_13_AVG','Tc_14_AVG',...
                'Tc_15_AVG','Tc_16_AVG','Tc_17_AVG','Tc_18_AVG','Tc_19_AVG',...
                'Tc_20_AVG','Tc_21_AVG','Tc_22_AVG','Tc_23_AVG','Tc_24_AVG',...
                'Tc_25_AVG','Tc_1_MAX','Tc_2_MAX','Tc_3_MAX','Tc_4_MAX','Tc_5_MAX',...
                'Tc_6_MAX','Tc_7_MAX','Tc_8_MAX','Tc_9_MAX','Tc_10_MAX','Tc_11_MAX',...
                'Tc_12_MAX','Tc_13_MAX','Tc_14_MAX','Tc_15_MAX','Tc_16_MAX','Tc_17_MAX',...
                'Tc_18_MAX','Tc_19_MAX','Tc_20_MAX','Tc_21_MAX','Tc_22_MAX','Tc_23_MAX',...
                'Tc_24_MAX','Tc_25_MAX','Tc_MIN','Tc_2_MIN','Tc_3_MIN','Tc_4_MIN','Tc_5_MIN',...
                'Tc_6_MIN','Tc_7_MIN','Tc_8_MIN','Tc_9_MIN','Tc_10_MIN','Tc_11_MIN',...
                'Tc_12_MIN','Tc_13_MIN','Tc_14_MIN','Tc_15_MIN','Tc_16_MIN','Tc_17_MIN',...
                'Tc_18_MIN','Tc_19_MIN','Tc_20_MIN','Tc_21_MIN','Tc_22_MIN','Tc_23_MIN',...
                'Tc_24_MIN','Tc_25_MIN','Tc_STD','Tc_2_STD','Tc_3_STD','Tc_4_STD','Tc_5_STD',...
                'Tc_6_STD','Tc_7_STD','Tc_8_STD','Tc_9_STD','Tc_10_STD','Tc_11_STD','Tc_12_STD',...
                'Tc_13_STD','Tc_14_STD','Tc_15_STD','Tc_16_STD','Tc_17_STD','Tc_18_STD',...
                'Tc_19_STD','Tc_20_STD','Tc_21_STD','Tc_22_STD','Tc_23_STD','Tc_24_STD',...
                'Tc_25_STD','VWC_1_AVG','Ts_1_AVG','VWC_2_AVG','Ts_2_AVG','VWC_3_AVG','Ts_3_AVG',...
                'VWC_4_AVG','Ts_4_AVG','VWC_5_AVG','Ts_5_AVG','VWC_6_AVG','Ts_6_AVG','VWC_7_AVG',...
                'Ts_7_AVG','VWC_8_AVG','Ts_8_AVG','VWC_9_AVG','Ts_9_AVG','VWC_10_AVG','Ts_10_AVG',...
                'VWC_11_AVG','Ts_11_AVG','VWC_12_AVG','Ts_12_AVG','VWC_13_AVG','Ts_13_AVG',...
                'VWC_14_AVG','Ts_14_AVG','VWC_15_AVG','Ts_15_AVG','VWC_16_AVG','Ts_16_AVG',...
                'VWC_17_AVG','Ts_17_AVG','VWC_18_AVG','Ts_18_AVG','VWC_19_AVG','Ts_19_AVG',...
                'VWC_20_AVG','Ts_20_AVG','VWC_21_AVG','Ts_21_AVG','VWC_22_AVG','Ts_22_AVG','VWC_23_AVG',...
                'Ts_23_AVG','VWC_24_AVG','Ts_24_AVG','VWC_1_MAX','Ts_1_MAX','VWC_2_MAX','Ts_2_MAX',...
                'VWC_3_MAX','Ts_3_MAX','VWC_4_MAX','Ts_4_MAX','VWC_5_MAX','Ts_5_MAX','VWC_6_MAX',...
                'Ts_6_MAX','VWC_7_MAX','Ts_7_MAX','VWC_8_MAX','Ts_8_MAX','VWC_9_MAX','Ts_9_MAX',...
                'VWC_10_MAX','Ts_10_MAX','VWC_11_MAX','Ts_11_MAX','VWC_12_MAX','Ts_12_MAX',...
                'VWC_13_MAX','Ts_13_MAX','VWC_14_MAX','Ts_14_MAX','VWC_15_MAX','Ts_15_MAX','VWC_16_MAX',...
                'Ts_16_MAX','VWC_17_MAX','Ts_17_MAX','VWC_18_MAX','Ts_18_MAX','VWC_19_MAX','Ts_19_MAX',...
                'VWC_20_MAX','Ts_20_MAX','VWC_21_MAX','Ts_21_MAX','VWC_22_MAX','Ts_22_MAX','VWC_23_MAX',...
                'Ts_23_MAX','VWC_24_MAX','Ts_24_MAX','VWC_1_MIN','Ts_1_MIN','VWC_2_MIN','Ts_2_MIN',...
                'VWC_3_MIN','Ts_3_MIN','VWC_4_MIN','Ts_4_MIN','VWC_5_MIN','Ts_5_MIN','VWC_6_MIN',...
                'Ts_6_MIN','VWC_7_MIN','Ts_7_MIN','VWC_8_MIN','Ts_8_MIN','VWC_9_MIN','Ts_9_MIN',...
                'VWC_10_MIN','Ts_10_MIN','VWC_11_MIN','Ts_11_MIN','VWC_12_MIN','Ts_12_MIN','VWC_13_MIN',...
                'Ts_13_MIN','VWC_14_MIN','Ts_14_MIN','VWC_15_MIN','Ts_15_MIN','VWC_16_MIN','Ts_16_MIN',...
                'VWC_17_MIN','Ts_17_MIN','VWC_18_MIN','Ts_18_MIN','VWC_19_MIN','Ts_19_MIN','VWC_20_MIN',...
                'Ts_20_MIN','VWC_21_MIN','Ts_21_MIN','VWC_22_MIN','Ts_22_MIN','VWC_23_MIN','Ts_23_MIN',...
                'VWC_24_MIN','Ts_24_MIN','VWC_1_STD','Ts_1_STD','VWC_2_STD','Ts_2_STD','VWC_3_STD',...
                'Ts_3_STD','VWC_4_STD','Ts_4_STD','VWC_5_STD','Ts_5_STD','VWC_6_STD','Ts_6_STD',...
                'VWC_7_STD','Ts_7_STD','VWC_8_STD','Ts_8_STD','VWC_9_STD','Ts_9_STD','VWC_10_STD',...
                'Ts_10_STD','VWC_11_STD','Ts_11_STD','VWC_12_STD','Ts_12_STD','VWC_13_STD','Ts_13_STD',...
                'VWC_14_STD','Ts_14_STD','VWC_15_STD','Ts_15_STD','VWC_16_STD','Ts_16_STD','VWC_17_STD',...
                'Ts_17_STD','VWC_18_STD','Ts_18_STD','VWC_19_STD','Ts_19_STD','VWC_20_STD','Ts_20_STD',...
                'VWC_21_STD','Ts_21_STD','VWC_22_STD','Ts_22_STD','VWC_23_STD','Ts_23_STD','VWC_24_STD',...
                'Ts_24_STD','PanelT2_AVG','PumpBoxT2_AVG','PicarroT2_AVG','PanelT2_MAX','PumpBoxT2_MAX',...
                'PicarroT2_MAX','PanelT2_MIN','PumpBoxT2_MIN','PicarroT2_MIN','Pbar2_AVG','Pbar2_MAX','Pbar2_MIN',...
                'Pbar2_STD','ACPowerON2_AVG','ACPowerON2_MAX','ACPowerON2_MIN','ACPowerON2_STD','VWC_CH03_AVG',...
                'Ts_CH03_AVG','VWC_CH04_AVG','Ts_CH04_AVG','VWC_CH05_AVG','Ts_CH05_AVG','VWC_CH06_AVG',...
                'Ts_CH06_AVG','VWC_CH11_AVG','Ts_CH11_AVG','VWC_CH12_AVG','Ts_CH12_AVG','VWC_CH03_MAX',...
                'Ts_CH03_MAX','VWC_CH04_MAX','Ts_CH04_MAX','VWC_CH05_MAX','Ts_CH05_MAX','VWC_CH06_MAX',...
                'Ts_CH06_MAX','VWC_CH11_MAX','Ts_CH11_MAX','VWC_CH12_MAX','Ts_CH12_MAX','VWC_CH03_MIN',...
                'Ts_CH03_MIN','VWC_CH04_MIN','Ts_CH04_MIN','VWC_CH05_MIN','Ts_CH05_MIN','VWC_CH06_MIN',...
                'Ts_CH06_MIN','VWC_CH11_MIN','Ts_CH11_MIN','VWC_CH12_MIN','Ts_CH12_MIN','VWC_CH03_STD',...
                'Ts_CH03_STD','VWC_CH04_STD','Ts_CH04_STD','VWC_CH05_STD','Ts_CH05_STD','VWC_CH06_STD',...
                'Ts_CH06_STD','VWC_CH11_STD','Ts_CH11_STD','VWC_CH12_STD','Ts_CH12_STD'};

[~,~,~,dataOut_30min] = fr_read_csi_file(fileName,chanInd,varNames_102,tableID,timeUnit,roundType,tv_input_format);
