function  hndls = ta_create_interface(fig_top,local_use,list_of_traces)

%-----------------------------------------------------------------------
%controls:
cb_scroll_right = uicontrol( fig_top, 'style','push','Units','normalized',...
   'position',[0.75 0.005 0.04 0.04],'string','>',...
   'HorizontalAlignment','center',...
   'CallBack','TA_controls(''scroll_right'')');
cb_scroll_left = uicontrol( fig_top,'style','push','Units','normalized',...
   'position',[0.30 0.005 0.04 0.04],'string','<',...
   'HorizontalAlignment','center',...
   'CallBack','TA_controls(''scroll_left'')');
cb_end_right = uicontrol( fig_top,'style','push','Units','normalized',...
   'position',[0.7 0.005 0.04 0.04],'string','>>',...
   'HorizontalAlignment','center',...
   'CallBack','TA_controls(''end_right'')');
cb_end_left = uicontrol( fig_top,'style','push','Units','normalized',...
   'position',[0.35 0.005 0.04 0.04],'string','<<',...
   'HorizontalAlignment','center',...
   'CallBack','TA_controls(''end_left'')');
if strcmp(local_use,'no')
   h = uicontrol( fig_top,'style','push','Units','normalized',...
      'position',[.01 .005 .09 .04],...
      'string','Prev Trace','HorizontalAlignment','center',...
      'CallBack','TA_controls(''prev'')');
   h = uicontrol( fig_top,'style','push','Units','normalized',...
      'position',[.9 .005 .09 .04],...
      'string','Next Trace','HorizontalAlignment','center',...
      'CallBack','TA_controls(''next'')');
end

%-----------------------------------------------------------------------
%File menu
file_menu = uimenu('parent', fig_top,'Label','File');
%uimenu(file_menu,'Label','ReLoad Current Trace',...
 %  'Callback','TA_filemenu(''reload'')');
uimenu(file_menu,'Label','Save Trace Information',...
      'Callback','TA_filemenu(''save_mat_file'')');
% kai* June 14, 2001
% New menu point allows to quit point picking and continue with automatic
% cleaning on all loaded traces
uimenu(file_menu,'Label','Continue automatic cleaning',...
   'Callback','TA_filemenu(''quit'')');
% end kai*
uimenu(file_menu,'Label','Quit Program',...
   'Callback','TA_filemenu(''terminate'')','separator','on');

if ~isempty(list_of_traces)
	m_imptrc=uimenu('parent',fig_top,'Label','Import');
	m_curr_plot = uimenu('parent',m_imptrc,'Label','Traces to Bottom Plot');
	uimenu('parent',m_curr_plot,'label','Left Axis',...
      'Callback','TA_filemenu(''curr_same'')');
   uimenu('parent',m_curr_plot,'label','Right Axis',...
      'Callback','TA_filemenu(''curr_new'')');
   m_new_plot = uimenu('parent',m_imptrc,'Label','Traces to Top Plot');
   uimenu('parent',m_new_plot,'label','Left Axis',...
     'Callback','TA_filemenu(''next_same'')');
   uimenu('parent',m_new_plot,'label','Right Axis',...
      'Callback','TA_filemenu(''next_new'')');
   m_new_plot = uimenu('parent',m_imptrc,'Label','Remove Traces','Separator','on',...
      'Callback','TA_filemenu(''rem_trc'')');
end

%-----------------------------------------------------------------------
%Option menu
options_menu = uimenu('parent',fig_top,'Label','Options');
m_select = uimenu(options_menu,'Label','Selection Type: Exact',...
   'Callback','TA_optionmenu(''exact'')');
m_style = uimenu(options_menu,'Label','Plot Properties',...
   'Callback','TA_optionmenu(''lin_style'')');
m_style = uimenu(options_menu,'Label','Axes Properties',...
   'Callback','TA_optionmenu(''ax_opts'')');
m_style = uimenu(options_menu,'Label','View Legend',...
   'Callback','TA_optionmenu(''legend'')');

%-----------------------------------------------------------------------
%Advanced Menu
adv_menu = uimenu('parent', fig_top,'Label','Advanced');
m_filt = uimenu(adv_menu,'Label','Filter Envelopes');
a_viewFilt = uimenu('parent',m_filt,'Label','View Current',...
   'Callback','TA_advancedmenu(''view_env'')');
uimenu('parent',m_filt,'Label','Create New',...
   'Callback','TA_advancedmenu(''create_env'')');
uimenu('parent',m_filt,'Label','Remove Last',...
   'Callback','TA_advancedmenu(''remove_env'')');
a_interp = uimenu(adv_menu,'Label','Change Linear Interpolation Length',...
   'Callback','TA_advancedmenu(''interp_set'')');

if strcmp(local_use,'no')
   m_interp = uimenu(adv_menu,'Label','Remove Points in Multiple Traces',...
      'Callback','TA_advancedmenu(''rem_pts_traces'')','separator','on');
   m_interp = uimenu(adv_menu,'Label','Restore Points in Multiple Traces',...
      'Callback','TA_advancedmenu(''restore_mult_traces'')');
end

m_statsnmenu = uimenu('parent', fig_top,'Label','Statistics');
m_clStats = uimenu(m_statsnmenu,'Label','View Stats of Selected Points',...
   'Callback','TA_statsmenu(''curr_pts'')');
m_clStats = uimenu(m_statsnmenu,'Label','View All Cleaning Results',...
   'Callback','TA_statsmenu(''stats'')');

%-----------------------------------------------------------------------
%Help menu
help_menu = uimenu('parent', fig_top,'Label','Help');
m_help = uimenu(help_menu,'Label','Commands','Callback',...
   'TA_help_menu(''init'')');

hndls = [m_select a_viewFilt];