---
title: "Data QCQA" 
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(ggplot2)
library(ggpubr)
library(forecast)
library(lubridate)
library(hms)
library(gridExtra)
library(amerifluxr)
library(heatmaply)
library(data.table)
library(ggpmisc)
library(knitr)
```

<!-- specify init file to read -->
```{r echo=FALSE, include=FALSE}
read_chunk('ini_files/DSM_v2_data_QCQA.R')
```

```{r, echo=FALSE, include=FALSE}
<<LoadData>>
```

```{r}
data(iris)
```

```{r echo=FALSE}
# Comments/Notes
# 1) See if want to update sonic, temperature, and rad plots using multiple_plotlys

# 2) NEED TO ADD 7200, 7700 temp and 7200 RH & CHECK WHICH TEMP IS USED TO SONIC (cross wind corrected or no) ADD HERE after MEETING ON THURSDAY!
# 3) Try to track down WD_CUP at all sites
# 4) Remove duplicate variables (e.g., see google sheets for tracking)
# 5) Think about output directory (can change by replacing 'dirname(inputFile)' above)
# 6) Add EBC
```

<!-- specify init file to read -->
```{r echo=FALSE, include=FALSE}
read_chunk('ini_files/DSM_v2_data_QCQA.R')
```

```{r, echo=FALSE, include=FALSE}
<<LoadData>>
```

Single met 
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput('y', 'Variable', names(data[, !names(data) %in% c("datetime")])) 
```

Column
-----------------------------------------------------------------------

### Time series of single met variables

```{r}
dataset <- reactive({
  data[, c(input$x, input$y)]
})

renderPlotly({
  plot_ly(data, x = ~datetime, y = ~data[[input$y]], type = 'scatter', mode = 'lines') %>%
  layout(yaxis = list(title = input$y)) %>%
    toWebGL() 
})
```

### Plot mean diurnal pattern

```{r}



dataset <- reactive({
  diurnal.summary(data, input$y, 30, 15)

 })

  
  renderPlotly({
    
    
 # diurnal.summary.composite <- diurnal.summary %>%
  #  group_by(firstdate,HHMM) %>%
  #  dplyr::summarize(var = median(input$y, na.rm = TRUE),
       #              HHMM = first(HHMM))
 # diurnal.summary.composite$time <- as.POSIXct(as.character(diurnal.summary.composite$HHMM), format="%R", tz="UTC")

    # p <- ggplot(dataset(), aes_string(x = "datetime", y = input$y)) +
    # geom_point()
    # p
    
     diurnal.summary.composite <- dataset() %>%
    group_by(firstdate,HHMM) %>%
    dplyr::summarize(var = median(var, na.rm = TRUE),
                     HHMM = first(HHMM))
  diurnal.summary.composite$time <- as.POSIXct(as.character(diurnal.summary.composite$HHMM), format="%R", tz="UTC")
  
  p <- ggplot() +
    geom_point(data = dataset(), aes(x = time, y = var),color = 'Grey',size = 0.1) +
    geom_line(data = diurnal.summary.composite, aes(x = time, y = var),color = 'Black') +
    scale_x_datetime(breaks="6 hours", date_labels = "%R") + ylab(input$y)
  p <- ggplotly(p+ facet_wrap(~as.factor(firstdate))) %>% toWebGL()
  p
  
  #    p <- ggplot(dataset(), aes(x = time, y = var)) +
  #   geom_point() 
  # p <- ggplotly(p+ facet_wrap(~as.factor(firstdate))) %>% toWebGL()
  # p
  
  # p <- ggplotly(p+ facet_wrap(~as.factor(firstdate))) %>% toWebGL()
  # p
  # 
  # plot_ly(data = data, x = ~datetime, y = as.formula(paste0("~",input$y)), type = 'scatter', mode = 'lines') %>%
  # layout(yaxis = list(title = input$y)) %>%
  #   toWebGL() 
})
```
