---
title: "Data QCQA"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(ggplot2)
library(ggpubr)
library(forecast)
library(lubridate)
library(hms)
library(gridExtra)
library(amerifluxr)
library(heatmaply)
library(data.table)
library(ggpmisc)
library(knitr)
library(stringr)

source("ini_files/DSM_data_QCQA.R")
```

```{r echo=FALSE}
# Comments/Notes
# 1) See if want to update sonic, temperature, and rad plots using multiple_plotlys

# 2) NEED TO ADD 7200, 7700 temp and 7200 RH & CHECK WHICH TEMP IS USED TO SONIC (cross wind corrected or no) ADD HERE after MEETING ON THURSDAY!
# 3) Try to track down WD_CUP at all sites
# 4) Remove duplicate variables (e.g., see google sheets for tracking)
# 5) Think about output directory (can change by replacing 'dirname(inputFile)' above)
# 6) Add EBC
```

Flux time series 
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput('f', 'Variable', flux_vars) 

if (exists("data_thirdstage") == TRUE) {
  selectInput('f3', 'Gap-filled Variable', flux_vars_gf) 
}
```

Column
-----------------------------------------------------------------------

### Time series of single flux variable

```{r}

dataset_flux <- reactive({
  data[, c("datetime", input$f)]
})

if (exists("data_thirdstage") == TRUE) {
  
  dataset_thirdstage <- reactive({
    data_thirdstage[, c(input$f3)]
  })
}

renderPlotly({
  
  colors = c("gap-filled" = "black", "Second stage" = rgb(0.2, 0.6, 0.9, 1), "Third stage" = "#69b3a2")
  
  if (exists("data_thirdstage") == TRUE) {
    
    df <- cbind(dataset_flux(), dataset_thirdstage(),data_thirdstage[, input$f])
    colnames(df) <- c("datetime","gap_filled","second_stage","third_stage")
    
    p <- ggplot(data = df) +
      geom_line(aes_string(x = "datetime", y = "gap_filled",color = shQuote("Gap-filled")))+
      geom_line(aes_string(x = "datetime", y = "second_stage", color = shQuote("Second stage")))+
      geom_line(aes_string(x = "datetime", y = "third_stage", color = shQuote("Third stage")))+
      xlab("") + ylab(input$f) +
      scale_color_manual(values = colors) + labs(color = "Trace")
    p <- ggplotly(p) %>% toWebGL()
    
  } else {
    
    df <- cbind(dataset_flux())
    colnames(df) <- c("datetime","second_stage")
    
    p <- ggplot(data = df) +
      geom_line(aes_string(x = "datetime", y = "second_stage", color = shQuote("Second stage")))+
      xlab("") + ylab(input$f) +
      scale_color_manual(values = colors) + labs(color = "Trace")
    p <- ggplotly(p) %>% toWebGL()}
  
})

```

Flux summary
=======================================================================

```{r}
if (exists("data_thirdstage") == TRUE) {
  # Create conversion factors
  conv_factor <- data.frame(44.01/(10^6)*(60*30),16.04/(10^9)*(60*30),(60*30)/(10^6))
  colnames(conv_factor) <- c("CO2","CH4","Energy")
  
  # Create string for conversion factor variable names
  conv_factor_vars <- c("CO2","CH4","Energy")
}
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}

if (exists("data_thirdstage") == TRUE) {
  selectInput('fl3', 'Gap-filled Variable', flux_vars_gf) 
}
if (exists("data_thirdstage") == TRUE) {
  selectInput('conv', 'Conversion factor for cumulative flux', conv_factor_vars) 
}
```

Column {data-width=600}
-----------------------------------------------------------------------

### Daily mean time series of single flux variable by year (need stage 3 data)

```{r}

if (exists("data_thirdstage") == TRUE) {
  dataset_thirdstage_daily <- reactive({
    data_thirdstage[, c("year","DOY", input$fl3)]
  })
}

renderPlotly({
  
  if (exists("data_thirdstage") == TRUE) {
    
    df <- dataset_thirdstage_daily()
    colnames(df)[3] <- "var"
    
    daily.data <- df %>%
      group_by(year,DOY) %>%
      dplyr::summarize(var = median(var, na.rm = TRUE),
                       DOY = first(DOY),
                       year = as.factor(first(year)))
    
    p <- ggplot() +
      geom_line(data = daily.data , aes(x = DOY, y = var, color = year))+ 
      ylab(input$fl3)
    p <- ggplotly(p) %>% toWebGL()
  }
})
```

Column {data-width=400}
-----------------------------------------------------------------------

### Cumulative flux

```{r}

if (exists("data_thirdstage") == TRUE) {
  
  dataset_thirdstage_cum <- reactive({
    data_thirdstage[, c("year","DOY", input$fl3)]
  })
  
  convfactor <- reactive({
    conv_factor[ ,c(input$conv)]
  })
  
  renderPlotly({
    
    df <- dataset_thirdstage_cum()
    colnames(df)[3] <- "var"
    
    cf <- convfactor()
    
    daily.cum <- df %>%
      group_by(year,DOY) %>%
      dplyr::summarize(var = sum(var*cf), 
                       DOY = first(DOY),
                       year = as.factor(first(year)))
    daily.cum$var_cum <- cumsum(daily.cum$var)
    
    p <- ggplot() +
      geom_line(data = daily.cum, aes(x = DOY, y = var_cum, color = year))+ 
      ylab(input$fl3)
    p <- ggplotly(p) %>% toWebGL()
    
  })
}
```

### Mean diurnal pattern

```{r}

if (exists("data_thirdstage") == TRUE) {
  
  dataset_thirdstage_diurnal <- reactive({
    data_thirdstage[, c("datetime", input$fl3)]
  })
  
  renderPlotly({
    
    colname <- colnames(dataset_thirdstage_diurnal())
    var_in <-  str_split(colname[2],"_")
    
    df <- data_thirdstage[, c("datetime", var_in[[1]][1])]
    colnames(df)[2] <- "var"
    
    data.diurnal <- df %>%
      mutate(
        year = as.factor(year(datetime)),
        month = month(datetime),
        day = day(datetime),
        jday = yday(datetime),
        hour = hour(datetime),
        minute = minute(datetime),
        HHMM = format(as.POSIXct(datetime), format = "%H:%M")
      ) %>%  # Create hour and minute variable (HHMM)
      group_by(year, HHMM) %>%
      dplyr::summarize(var = median(var,na.rm = TRUE))
    
    data.diurnal$time <- as.POSIXct(as.character(data.diurnal$HHMM), format="%R", tz="UTC")
    
    p <- ggplot() +
      geom_line(data = data.diurnal, aes(x = time, y = var,color = year)) +
      scale_x_datetime(breaks="6 hours", date_labels = "%R") + ylab(var_in[[1]][1])
    
    p <- ggplotly(p) %>% toWebGL()
    p
    
  })
}
```

Flux diagnostics
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Flux diagnostics
```{r}
flux_diagnostic_plots(data,vars_flux_diag)
```

Column {data-width=400}
-----------------------------------------------------------------------

### EBC half-hourly
```{r}
scatter_plot_QCQA_EBC(data_thirdstage,vars_EBC_AE,c("H","LE"),"AE  (W m-2)","H+LE (W m-2)")
```

### EBC daily
```{r}
scatter_plot_QCQA_EBC_daily(data_thirdstage,vars_EBC_AE,c("H","LE"),"AE  (W m-2)","H+LE (W m-2)")
```

