function runThirdStageCleaningREddyProc(yearIn,siteID)
% runThirdStageCleaningREddyProc(yearIn,siteID)
%
% This function invokes Micromet third-stage cleaning R-script.
% Usually, it's called from fr_automated_cleaning()
%
%
% Zoran Nesic               File created:       Oct 25, 2022
%                           Last modification:  Oct 28, 2022
%

% Revisions
%

    if ~ispc
        error('This function is not compatible with macOS, yet!\n');
    end
    
    strYearIn = num2str(yearIn);

    % find path to R database_functions folder
    pthBiometR = findBiometRpath;
    % find path to database
    pthDatabase = findDatabasePath;

    % This one should be under ../Database/Calculation_procedures\TraceAnalysis_ini\siteID:
    pthBatch = fullfile(pthDatabase,'Calculation_procedures','TraceAnalysis_ini',siteID);

    % Find path to the newest version of Rscript
    pthRbin = findRPath;    

    % create all file paths
    % log files go under ../database/Calculation_Procedures\TraceAnalysis_ini\siteID\log
    if ~exist(fullfile(pthBatch,'log'),'dir')
        mkdir(fullfile(pthBatch,'log'))
    end    
    pthLogFile = fullfile(pthBatch,'log',[siteID '_ThirdStageCleaning.log']);
    % the *.bat file that runs Rscript also goes into the log folder 
    pthBatchFile = fullfile(pthBatch,'log',[siteID '_ThirdStageCleaning.bat']);
    % The cleaning script Run_REddyProc_ThirdStage_siteID.R is under ../Biomet.net/R
    pthCleaningScript = fullfile(pthBiometR,['Run_REddyProc_ThirdStage_' siteID '.R']);
    % create the batch file command line 
    cmdLine = ['"' pthRbin '" "'  pthCleaningScript '" ' siteID ...
               ' ' strYearIn ' "' pthDatabase '" "' pthBiometR '" ' ...
               ' 2> "' pthLogFile '" 1>&2'];
    tic;
    tv_start = now;
    % Create the batch file that calls R
    st=dbstack;
    fidBatch = fopen(pthBatchFile,'w');
    if fidBatch>0
        fprintf(fidBatch,'REM ----------------------------------------------------------\n');
        fprintf(fidBatch,'REM  This file is automatically generated by Matlab function:\n');
        fprintf(fidBatch,'REM  %s.m\n',st(1).name);
        fprintf(fidBatch,'REM  %s\n',datestr(now));
        fprintf(fidBatch,'REM ----------------------------------------------------------\n');
        fprintf(fidBatch,'%s\n',cmdLine);
        fclose(fidBatch);
        [~,cmdOutput] = system(pthBatchFile); %#ok<ASGLU>
    end

    % When R is finshed, print the footer in the log file
    fidLog = fopen(pthLogFile,'a');      
    if fidLog > 0    
        fprintf(fidLog,'\n\n\n\n');
        fprintf(fidLog,'=============================================================\n');
        fprintf(fidLog,'Rscript:      %s\n',pthRbin);
        fprintf(fidLog,'Start:        %s\n',datestr(tv_start));
        fprintf(fidLog,'End:          %s\n',datestr(now));
        fprintf(fidLog,'Elapsed time: %6.1f min\n',toc/60);
        fprintf(fidLog,'==============================================================\n'); 
        fclose(fidLog);
    end

end

function biometRpath = findBiometRpath
    funA = which('read_bor');     % First find the path to Biomet.net by looking for a standard Biomet.net functions
    tstPattern = [filesep 'Biomet.net' filesep];
    indFirstFilesep=strfind(funA,tstPattern);
    biometRpath = fullfile(funA(1:indFirstFilesep-1),tstPattern,'R', 'database_functions');
end

function databasePath = findDatabasePath
    databasePath = biomet_path('yyyy');
    indY = strfind(databasePath,'yyyy');
    databasePath = databasePath(1:indY-2); 
end

function Rpath = findRPath
    pathMatlab = matlabroot;
    indY = strfind(upper(pathMatlab),[filesep 'MATLAB']);
    pathBin = fullfile(pathMatlab(1:indY-1));
    s = dir(fullfile(pathBin,'R','R-*')); 
    if length(s) < 1
        error ('Cannot find location of R inside of %s\n',pathBin);
    end
    Rpath = "";
    N = 0;
    for cntFolders = 1:length(s)
        if s(cntFolders).name > Rpath
            Rpath = s(cntFolders).name;
            N = cntFolders;
        end
    end
    Rpath = fullfile(s(N).folder,s(N).name,'bin','Rscript.exe');
end
        

